### ISSUE TITLE
os is not defined - utils.py

### ISSUE THREAD

**Issue by 2022tgoel** [jlevy44/PathPretrain#1]
Hi, so I'm running into to following issue when trying to run pathpretrain-preprocess on the arctic whole slide images:
```
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/9/f005q19/anaconda3/envs/arctic/bin/pathpretrain-preprocess", line 8, in <module>
    sys.exit(main())
  File "/dartfs-hpc/rc/home/9/f005q19/anaconda3/envs/arctic/lib/python3.7/site-packages/pathpretrain/preprocess.py", line 80, in main
    fire.Fire(preprocess)
  File "/dartfs-hpc/rc/home/9/f005q19/anaconda3/envs/arctic/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/dartfs-hpc/rc/home/9/f005q19/anaconda3/envs/arctic/lib/python3.7/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/dartfs-hpc/rc/home/9/f005q19/anaconda3/envs/arctic/lib/python3.7/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/dartfs-hpc/rc/home/9/f005q19/anaconda3/envs/arctic/lib/python3.7/site-packages/pathpretrain/preprocess.py", line 58, in preprocess
    image=load_image(image_file)
  File "/dartfs-hpc/rc/home/9/f005q19/anaconda3/envs/arctic/lib/python3.7/site-packages/pathpretrain/utils.py", line 26, in load_image
    img_ext=os.path.splitext(image_file)
NameError: name 'os' is not defined
```

when I look at https://github.com/jlevy44/PathPretrain/blob/master/pathpretrain/utils.py I don't see that you import os, which may be the issue?

**Comment by jlevy44** [comment]
In latest push!
